/**
 * NullForge Chrome Extension - Popup Script
 * AI-powered code synthesis from any webpage
 */

// State
let isProcessing = false;

// DOM Elements
const goalInput = document.getElementById('goalInput');
const providerSelect = document.getElementById('providerSelect');
const modelSelect = document.getElementById('modelSelect');
const synthesizeBtn = document.getElementById('synthesizeBtn');
const loading = document.getElementById('loading');
const resultPanel = document.getElementById('resultPanel');
const resultCode = document.getElementById('resultCode');
const copyBtn = document.getElementById('copyBtn');
const statusBadge = document.getElementById('statusBadge');

// Provider models mapping
const providerModels = {
  venice: ['llama-3.1-405b', 'llama-3.1-70b', 'dolphin-2.9.2-qwen2-72b'],
  openai: ['gpt-4-turbo-preview', 'gpt-4o', 'gpt-3.5-turbo'],
  anthropic: ['claude-3-5-sonnet-20241022', 'claude-3-opus-20240229'],
  ollama: ['llama3.1:70b', 'deepseek-coder-v2:latest', 'dolphin-mixtral']
};

// Initialize
document.addEventListener('DOMContentLoaded', async () => {
  // Load saved settings
  const settings = await chrome.storage.sync.get(['provider', 'model', 'apiKey']);
  if (settings.provider) {
    providerSelect.value = settings.provider;
    updateModels();
    if (settings.model) {
      modelSelect.value = settings.model;
    }
  }
  
  // Load stats
  loadStats();
  
  // Check API connection
  checkConnection();
  
  // Get selected text from active tab
  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    const result = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      function: () => window.getSelection().toString()
    });
    if (result[0].result) {
      goalInput.value = `Based on this: "${result[0].result.substring(0, 500)}..."`;
    }
  } catch (e) {
    // Ignore errors from restricted pages
  }
});

// Update models when provider changes
providerSelect.addEventListener('change', () => {
  updateModels();
  saveSettings();
});

modelSelect.addEventListener('change', saveSettings);

function updateModels() {
  const provider = providerSelect.value;
  const models = providerModels[provider] || [];
  modelSelect.innerHTML = models.map(m => `<option value="${m}">${m}</option>`).join('');
}

async function saveSettings() {
  await chrome.storage.sync.set({
    provider: providerSelect.value,
    model: modelSelect.value
  });
}

// Synthesize button click
synthesizeBtn.addEventListener('click', async () => {
  const goal = goalInput.value.trim();
  if (!goal || isProcessing) return;
  
  isProcessing = true;
  synthesizeBtn.disabled = true;
  loading.classList.add('active');
  resultPanel.classList.remove('active');
  
  try {
    const result = await synthesize(goal);
    showResult(result);
    incrementStats();
  } catch (error) {
    showError(error.message);
  } finally {
    isProcessing = false;
    synthesizeBtn.disabled = false;
    loading.classList.remove('active');
  }
});

async function synthesize(goal) {
  const settings = await chrome.storage.sync.get(['apiKey', 'apiBase']);
  
  // For demo, simulate API call
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  // Simulated response
  const code = `# Generated by NullForge
# Goal: ${goal.substring(0, 50)}...

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(title="Generated API")

class Item(BaseModel):
    id: Optional[int] = None
    name: str
    description: Optional[str] = None

items: List[Item] = []

@app.get("/items", response_model=List[Item])
async def get_items():
    return items

@app.post("/items", response_model=Item)
async def create_item(item: Item):
    item.id = len(items) + 1
    items.append(item)
    return item

@app.get("/items/{item_id}", response_model=Item)
async def get_item(item_id: int):
    for item in items:
        if item.id == item_id:
            return item
    raise HTTPException(status_code=404, detail="Item not found")
`;
  
  return code;
}

function showResult(code) {
  resultCode.textContent = code;
  resultPanel.classList.add('active');
  
  // Save to history
  saveToHistory(goalInput.value, code);
}

function showError(message) {
  resultCode.textContent = `Error: ${message}`;
  resultPanel.classList.add('active');
  document.querySelector('.result-title').textContent = '✗ Error';
  document.querySelector('.result-title').style.color = '#ef4444';
}

// Copy to clipboard
copyBtn.addEventListener('click', async () => {
  await navigator.clipboard.writeText(resultCode.textContent);
  copyBtn.textContent = '✓';
  setTimeout(() => copyBtn.textContent = '📋', 1500);
});

// Quick actions
document.getElementById('scanPageBtn').addEventListener('click', async () => {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  
  chrome.scripting.executeScript({
    target: { tabId: tab.id },
    function: scanPage
  });
  
  window.close();
});

document.getElementById('extractCodeBtn').addEventListener('click', async () => {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  
  const result = await chrome.scripting.executeScript({
    target: { tabId: tab.id },
    function: extractCode
  });
  
  if (result[0].result) {
    goalInput.value = `Improve this code:\n${result[0].result.substring(0, 1000)}`;
  }
});

document.getElementById('auditBtn').addEventListener('click', () => {
  goalInput.value = 'Perform a security audit on the current page and identify vulnerabilities';
});

document.getElementById('historyBtn').addEventListener('click', async () => {
  const history = await chrome.storage.local.get('history');
  console.log('History:', history);
  alert('History feature coming soon!');
});

document.getElementById('settingsLink').addEventListener('click', (e) => {
  e.preventDefault();
  chrome.runtime.openOptionsPage();
});

document.getElementById('dashboardLink').addEventListener('click', (e) => {
  e.preventDefault();
  chrome.tabs.create({ url: 'https://nullforge.io/dashboard' });
});

// Helper functions
function scanPage() {
  // Inject scanning UI
  const overlay = document.createElement('div');
  overlay.id = 'nullforge-scanner';
  overlay.innerHTML = `
    <div style="position: fixed; top: 20px; right: 20px; background: linear-gradient(135deg, #0a0a0f, #12121a); 
                color: white; padding: 20px; border-radius: 12px; z-index: 999999; font-family: system-ui;
                border: 1px solid rgba(139, 92, 246, 0.3); box-shadow: 0 10px 40px rgba(0,0,0,0.5);">
      <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 15px;">
        <span style="font-size: 24px;">⚡</span>
        <span style="font-weight: 600;">NullForge Scanner</span>
      </div>
      <div style="color: #a0a0b0; font-size: 13px;">Analyzing page structure...</div>
      <div style="margin-top: 15px; height: 4px; background: #1a1a25; border-radius: 2px; overflow: hidden;">
        <div style="height: 100%; width: 0%; background: linear-gradient(90deg, #00d4ff, #8b5cf6); 
                    animation: scan 2s ease-in-out forwards;" id="scanProgress"></div>
      </div>
    </div>
    <style>
      @keyframes scan { to { width: 100%; } }
    </style>
  `;
  document.body.appendChild(overlay);
  
  setTimeout(() => {
    overlay.remove();
  }, 3000);
}

function extractCode() {
  const codeBlocks = document.querySelectorAll('pre code, pre, code');
  let code = '';
  codeBlocks.forEach(block => {
    code += block.textContent + '\n\n';
  });
  return code.trim();
}

async function saveToHistory(goal, result) {
  const history = (await chrome.storage.local.get('history')).history || [];
  history.unshift({
    goal: goal.substring(0, 100),
    timestamp: Date.now(),
    provider: providerSelect.value
  });
  // Keep last 50 entries
  await chrome.storage.local.set({ history: history.slice(0, 50) });
}

async function loadStats() {
  const stats = await chrome.storage.local.get(['todaySynths', 'successRate', 'tokensUsed']);
  document.getElementById('todaySynths').textContent = stats.todaySynths || '0';
  document.getElementById('successRate').textContent = (stats.successRate || 94) + '%';
  document.getElementById('tokensUsed').textContent = formatNumber(stats.tokensUsed || 0);
}

async function incrementStats() {
  const stats = await chrome.storage.local.get(['todaySynths', 'tokensUsed']);
  const today = new Date().toDateString();
  const lastDate = (await chrome.storage.local.get('lastDate')).lastDate;
  
  let synths = stats.todaySynths || 0;
  if (lastDate !== today) {
    synths = 0;
  }
  synths++;
  
  const tokens = (stats.tokensUsed || 0) + Math.floor(Math.random() * 500 + 500);
  
  await chrome.storage.local.set({
    todaySynths: synths,
    tokensUsed: tokens,
    lastDate: today
  });
  
  document.getElementById('todaySynths').textContent = synths;
  document.getElementById('tokensUsed').textContent = formatNumber(tokens);
}

function formatNumber(num) {
  if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
  if (num >= 1000) return (num / 1000).toFixed(1) + 'k';
  return num.toString();
}

async function checkConnection() {
  // Simulate connection check
  const settings = await chrome.storage.sync.get(['apiKey']);
  if (!settings.apiKey) {
    statusBadge.textContent = 'Demo Mode';
    statusBadge.style.background = 'rgba(245, 158, 11, 0.3)';
    statusBadge.style.color = '#f59e0b';
  }
}

// Keyboard shortcut
document.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
    synthesizeBtn.click();
  }
});
